name: renovate

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    uses: jr200-labs/github-action-templates/.github/workflows/renovate.yaml@master
    secrets:
      app_private_key: ${{ secrets.INTEGRATION_APP_PRIVATE_KEY }}
